# Custom Language File for Launcher Customizer

[ejs.app]
title = "NOVACLIENT | Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO NOVA CLIENT"
welcomeDescription = "PLACEHOLDER"
welcomeDescCTA = "You are just a few clicks away from Nova Client."
